services:
  mongo:
    image: mongo:latest  
    container_name: chisai_mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password  
    volumes:
      - ./_docker_volumes/mongo:/data/db
      - ./_docker_volumes/mongo-config:/data/configdb

  redis:
    image: redis:alpine
    container_name: chisai_redis
    ports:
      - "6380:6379"
    volumes:
      - ./_docker_volumes/redis-data:/data


volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
  redis-data:
    driver: local
